version: 2

sources:
  - name: aliased_source
    database: dvdrental
    schema: public
    tables:
      - name: rental_all 
  - name: scratch
    database: dvdrental
    schema: valmi_scratch_computed_
    tables:
      - name: finalized_snapshot 
      - name: transit_snapshot 

models:
  - name: stg_snapshot
    description: This table has basic information about a customer, as well as some derived facts based on a customer's orders
