version: 2

sources:
  - name: jaffle_shop
    database: citus
    schema: dbt_rvarkala
    tables:
      - name: customers 
  - name: scratch
    database: citus
    schema: dbt_rvarkala
    tables:
      - name: finalized_snapshot 

models:
  - name: stg_snapshot
    description: This table has basic information about a customer, as well as some derived facts based on a customer's orders
