version: 2
 
models:
  - name: ignored_snapshot
    description: This table has basic information about a customer, as well as some derived facts based on a customer's orders
  - name: sync_metrics
    description: This table has basic information about a customer, as well as some derived facts based on a customer's orders
  - name: transit_snapshot
    description: This table has basic information about a customer, as well as some derived facts based on a customer's orders
